In [3]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as pl
import seaborn as sns


file_path = "D:\Data Science by SRK\Omkar Sir 10.30AM Batch\EDA\Visadataset.csv"

df = pd.read_csv(file_path)
df

,case_id,continent,education_of_employee,has_job_experience,requires_job_training,no_of_employees,yr_of_estab,region_of_employment,prevailing_wage,unit_of_wage,full_time_position,case_status
0,EZYV01,Asia,High School,N,N,14513,2007,West,592.2029,Hour,Y,Denied
1,EZYV02,Asia,Master's,Y,N,2412,2002,Northeast,83425.6500,Year,Y,Certified
2,EZYV03,Asia,Bachelor's,N,Y,44444,2008,West,122996.8600,Year,Y,Denied
3,EZYV04,Asia,Bachelor's,N,N,98,1897,West,83434.0300,Year,Y,Denied
4,EZYV05,Africa,Master's,Y,N,1082,2005,South,149907.3900,Year,Y,Certified
...,...,...,...,...,...,...,...,...,...,...,...,...
25475,EZYV25476,Asia,Bachelor's,Y,Y,2601,2008,South,77092.5700,Year,Y,Certified
25476,EZYV25477,Asia,High School,Y,N,3274,2006,Northeast,279174.7900,Year,Y,Certified
25477,EZYV25478,Asia,Master's,Y,N,1121,1910,South,146298.8500,Year,N,Certified
25478,EZYV25479,Asia,Master's,Y,Y,1918,1887,West,86154.7700,Year,Y,Certified
25479,EZYV25480,Asia,Bachelor's,Y,N,3195,1960,Midwest,70876.9100,Year,Y,Certified

In [15]:
df["continent"].value_counts()

continent
Asia             16861
Europe            3732
North America     3292
South America      852
Africa             551
Oceania            192
Name: count, dtype: int64

In [9]:
df1 = pd.DataFrame(df["continent"].value_counts())
df1

               count
continent
Asia           16861
Europe          3732
North America   3292
South America    852
Africa           551
Oceania          192

In [12]:
df1 = pd.DataFrame(df["continent"].value_counts()).reset_index()   # It will reset the index numbers as integer values starting from 0 
                                                                   # and the old indexes will became the columns values with column name as "index".
df1

       continent  count
0           Asia  16861
1         Europe   3732
2  North America   3292
3  South America    852
4         Africa    551
5        Oceania    192

In [37]:
cat = df.select_dtypes(include="object").columns
cat = cat.drop(cat[0])
d = pd.DataFrame()

for i in cat:
    df5 = pd.DataFrame(df[i].unique(),df[i].value_counts())
    d = pd.concat([d,df5])
    
d = d.reset_index()
d

    count              0
0   16861           Asia
1    3732         Africa
2    3292  North America
3     852         Europe
4     551  South America
5     192        Oceania
6   10234    High School
7    9634       Master's
8    3420     Bachelor's
9    2192      Doctorate
10  14802              N
11  10678              Y
12  22525              N
13   2955              Y
14   7195           West
15   7017      Northeast
16   6586          South
17   4307        Midwest
18    375         Island
19  22962           Hour
20   2157           Year
21    272           Week
22     89          Month
23  22773              Y
24   2707              N
25  17018         Denied
26   8462      Certified

In [40]:
d.columns = ["Counts","Labels"]
d

    Counts         Labels
0    16861           Asia
1     3732         Africa
2     3292  North America
3      852         Europe
4      551  South America
5      192        Oceania
6    10234    High School
7     9634       Master's
8     3420     Bachelor's
9     2192      Doctorate
10   14802              N
11   10678              Y
12   22525              N
13    2955              Y
14    7195           West
15    7017      Northeast
16    6586          South
17    4307        Midwest
18     375         Island
19   22962           Hour
20    2157           Year
21     272           Week
22      89          Month
23   22773              Y
24    2707              N
25   17018         Denied
26    8462      Certified