#### Importing the Packages

In [1]:
import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt

In [2]:
# pd.DataFrame(
#    data=None,
#    index: 'Axes | None' = None,
#    columns: 'Axes | None' = None,
#    dtype: 'Dtype | None' = None,
#    copy: 'bool | None' = None,)

df = pd.DataFrame(['Ramesh','Suresh','Satish'])
df

        0
0  Ramesh
1  Suresh
2  Satish

In [3]:
df = pd.DataFrame(data=['satish','ramesh','suresh'])
df

        0
0  satish
1  ramesh
2  suresh

In [4]:
df = pd.DataFrame(data=['ram','sam','raj'],columns=['Names'])
df

  Names
0   ram
1   sam
2   raj

In [5]:
df = pd.DataFrame(data=['ram','sam','raj'],index=['a','b','c'],columns=['Names'])
df

  Names
a   ram
b   sam
c   raj

#### How ro create a dataframe using a list

In [6]:
data=['sai','ram','krish']

df = pd.DataFrame(data)
df

       0
0    sai
1    ram
2  krish

In [7]:
data = ['sai','ram','jay']
index = [11,12,13]
age = [20,23,25]
column = ["Names"]
df = pd.DataFrame(data=data)
df

     0
0  sai
1  ram
2  jay

In [8]:
df["age"]=age
df

     0  age
0  sai   20
1  ram   23
2  jay   25

In [9]:
df = pd.DataFrame(data=data,columns=column,index=index)
df

   Names
11   sai
12   ram
13   jay

In [10]:
df['Age']=age
df

   Names  Age
11   sai   20
12   ram   23
13   jay   25

#### How to create a dataframe using dictionary

- while creating the dataframe using dictionary
  
   - keys becames column names
   - and values becomes rows data

In [47]:
d1 = {'Names':['sai','ram','sam'],'Age':[20,22,24],'City':['hyd','pune','mum']}

df = pd.DataFrame(d1)
df

  Names  Age  City
0   sai   20   hyd
1   ram   22  pune
2   sam   24   mum

In [12]:
d2 = {'Names':'sai','Age':20,'City':'hyd'}
df2 = pd.DataFrame(d2)

ValueError: If using all scalar values, you must pass an index

In [ ]:
d2 = {'Names':'sai','Age':20,'City':'hyd'}
df2 = pd.DataFrame(d2,index=[1])
df2

In [ ]:
d2 = {'Names':['sai'],'Age':[20],'City':['hyd']}
df2 = pd.DataFrame(d2)
df2

Step-1 : Create a DataFrame using list 
Step-2 : I want to change the index
Step-3 : Multiple columns
Step-4 : We have empty dataframe we need to add the data
Step-5 : How to create a DataFrame using a dictionary
Step-6 : Important dataframe methods
Step-7 : Rename the index and Columns all at a time. 
Step-8 : Rename Method
           - If we want to rename the indexes or columns we can use rename() method.

In [48]:
l = [1,2,3,34,5,6]

import pandas as pd

df = pd.DataFrame(l)
df

    0
0   1
1   2
2   3
3  34
4   5
5   6

In [49]:
id = ["a","b","c","d","e","f"]

df = pd.DataFrame(l,index=id)
df

    0
a   1
b   2
c   3
d  34
e   5
f   6

In [50]:
df.index = ["11","12","13","14","15","16"]
df

     0
11   1
12   2
13   3
14  34
15   5
16   6

In [52]:
df["Names"] = ["sai","ram","tej","vv","ab","jay"]
df

     0 Names
11   1   sai
12   2   ram
13   3   tej
14  34    vv
15   5    ab
16   6   jay

In [53]:
df["0"]=["Ranks"]

ValueError: Length of values (1) does not match length of index (6)

In [54]:
df.columns = ["Ranks","Names"]
df

    Ranks Names
11      1   sai
12      2   ram
13      3   tej
14     34    vv
15      5    ab
16      6   jay

# Step-8 : Rename Method
#            - If we want to rename the indexes or columns we can use rename() method.


df.rename(
    mapper: 'Renamer | None' = None,
    *,
    index: 'Renamer | None' = None,
    columns: 'Renamer | None' = None,
    axis: 'Axis | None' = None,
    copy: 'bool | None' = None,
    inplace: 'bool' = False,
    level: 'Level' = None,
    errors: 'IgnoreRaise' = 'ignore',
)



- In rename() method mapper means dictionary not list or set or tuple.

In [22]:
df

    Ranks Names
11      1   sai
12      2   ram
13      3   tej
14     34    vv
15      5    ab
16      6   jay

In [23]:
d = {"Ranks":"ranks"}

df.rename(mapper=d)   # It will not change the column name because bydefault axis=0 means it will applicable on rows or indexex not on columns.

    Ranks Names
11      1   sai
12      2   ram
13      3   tej
14     34    vv
15      5    ab
16      6   jay

In [24]:
df.rename(mapper=d,axis=1)  # It will change the columns names because here axis=1.

    ranks Names
11      1   sai
12      2   ram
13      3   tej
14     34    vv
15      5    ab
16      6   jay

In [26]:
print(df)
df.rename(columns={"Ranks":"ranks"})   # or df.rename(columns=d)

    Ranks Names
11      1   sai
12      2   ram
13      3   tej
14     34    vv
15      5    ab
16      6   jay

    ranks Names
11      1   sai
12      2   ram
13      3   tej
14     34    vv
15      5    ab
16      6   jay

# Drop Method : 

df.drop(
    labels: 'IndexLabel' = None,
    *,
    axis: 'Axis' = 0,
    index: 'IndexLabel' = None,
    columns: 'IndexLabel' = None,
    level: 'Level' = None,
    inplace: 'bool' = False,
    errors: 'IgnoreRaise' = 'raise',
)

In [29]:
df.drop("Ranks")   # It will gives error because by dafault axis=0, so it will search "ranks" index in row(index), not in columns.

KeyError: "['Ranks'] not found in axis"

In [30]:
df.drop("Ranks",axis=1)

   Names
11   sai
12   ram
13   tej
14    vv
15    ab
16   jay

In [32]:
df.drop(["Ranks"],axis=1)

   Names
11   sai
12   ram
13   tej
14    vv
15    ab
16   jay

In [34]:
df.drop(index="Ranks")   # It will not works because in rows there is no "Ranks" named row.

KeyError: "['Ranks'] not found in axis"

In [36]:
df.drop(index=["Ranks"])   # It will not works because in rows there is no "Ranks" named row.]

KeyError: "['Ranks'] not found in axis"

In [37]:
df.drop(columns="Ranks")   # It will drop the "Ranks" named column from the dataframe

   Names
11   sai
12   ram
13   tej
14    vv
15    ab
16   jay

In [38]:
df.drop(columns=["Ranks"])   # It will drop the "Ranks" named column from the dataframe

   Names
11   sai
12   ram
13   tej
14    vv
15    ab
16   jay

In [55]:
df.drop(columns=["Ranks","Names"])   # It will drop the Multiple colums from the dataframe at a time

Empty DataFrame
Columns: []
Index: [11, 12, 13, 14, 15, 16]

In [56]:
print(df.drop(columns="Ranks",inplace=False))  # It will only perform the drop opertion temperary, but it wull not drop the column permannetly. 
print(df)

   Names
11   sai
12   ram
13   tej
14    vv
15    ab
16   jay
    Ranks Names
11      1   sai
12      2   ram
13      3   tej
14     34    vv
15      5    ab
16      6   jay

In [57]:
print(df.drop(columns="Ranks",inplace=True))  # It will drop the column permannetly. 
print(df)

None
   Names
11   sai
12   ram
13   tej
14    vv
15    ab
16   jay

Replace Method :
    
df.replace(
    to_replace=None,
    value=<no_default>,
    *,
    inplace: 'bool' = False,
    limit: 'int | None' = None,
    regex: 'bool' = False,
    method: "Literal['pad', 'ffill', 'bfill'] | lib.NoDefault" = <no_default>,
)

In [101]:
df["Ranks"] = [1,2,2,4,5,6]
df

   Names  Ranks
11   sai      1
12   ram      2
13   tej      2
14    vv      4
15    ab      5
16   jay      6

In [102]:
df.replace(2,3)  # It will replace all the passing old values (including duplicates also) with passing new value.so it is bad thing when we want only one (duplicate) old value to replace with new value.

   Names  Ranks
11   sai      1
12   ram      3
13   tej      3
14    vv      4
15    ab      5
16   jay      6

In [103]:
df.loc["13"]   # It will access the total passing index number row.

Names    tej
Ranks      2
Name: 13, dtype: object

In [90]:
print(df.loc["13"].replace(2,3))  # It will replace the old row value with new row value by using index number, biut will replace temperary not permanent.
print(df)

Names    tej
Ranks      3
Name: 13, dtype: object
   Names  Ranks
11   sai      1
12   ram      2
13   tej      2
14    vv      4
15    ab      5
16   jay      6

In [104]:
df.loc["13"] = df.loc["13"].replace(2,3) # It will replace the old row value with new row value by using index number permanently.
print(df)

   Names  Ranks
11   sai      1
12   ram      2
13   tej      3
14    vv      4
15    ab      5
16   jay      6

In [106]:
print(df.replace("vv","viraj"))   # It will replace the old column value temperary with new value.
df

    Names  Ranks
11    sai      1
12    ram      2
13    tej      3
14  viraj      4
15     ab      5
16    jay      6

   Names  Ranks
11   sai      1
12   ram      2
13   tej      3
14    vv      4
15    ab      5
16   jay      6

#### Where Condition : 

     - np.where(<condition>,<If_cond_True>,<If_cond_False>)
     - np.where(<Write condition>, <If condition is true,then put that value by which we want to reaplece the old values>, <If condition false, then kept the old value as it is >)

In [95]:
df["Ranks"] = np.where(df["Ranks"]>3,"Participated",df["Ranks"] )   # Here "Participated" is new value with we want to replace the old value if condition is True. Otherwise we have kept the old values as it is idf condition is False
df

   Names         Ranks
11   sai             1
12   ram             2
13   tej             3
14    vv  Participated
15    ab  Participated
16   jay  Participated