In [47]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns


df = pd.read_csv("Visadataset.csv")
df

,case_id,continent,education_of_employee,has_job_experience,requires_job_training,no_of_employees,yr_of_estab,region_of_employment,prevailing_wage,unit_of_wage,full_time_position,case_status
0,EZYV01,Asia,High School,N,N,14513,2007,West,592.2029,Hour,Y,Denied
1,EZYV02,Asia,Master's,Y,N,2412,2002,Northeast,83425.6500,Year,Y,Certified
2,EZYV03,Asia,Bachelor's,N,Y,44444,2008,West,122996.8600,Year,Y,Denied
3,EZYV04,Asia,Bachelor's,N,N,98,1897,West,83434.0300,Year,Y,Denied
4,EZYV05,Africa,Master's,Y,N,1082,2005,South,149907.3900,Year,Y,Certified
...,...,...,...,...,...,...,...,...,...,...,...,...
25475,EZYV25476,Asia,Bachelor's,Y,Y,2601,2008,South,77092.5700,Year,Y,Certified
25476,EZYV25477,Asia,High School,Y,N,3274,2006,Northeast,279174.7900,Year,Y,Certified
25477,EZYV25478,Asia,Master's,Y,N,1121,1910,South,146298.8500,Year,N,Certified
25478,EZYV25479,Asia,Master's,Y,Y,1918,1887,West,86154.7700,Year,Y,Certified
25479,EZYV25480,Asia,Bachelor's,Y,N,3195,1960,Midwest,70876.9100,Year,Y,Certified

In [18]:
cat = df.select_dtypes(include="object").columns
cat

Index(['case_id', 'continent', 'education_of_employee', 'has_job_experience',
       'requires_job_training', 'region_of_employment', 'unit_of_wage',
       'full_time_position', 'case_status'],
      dtype='object')

In [19]:
num = df.select_dtypes(exclude="object").columns
num

Index(['no_of_employees', 'yr_of_estab', 'prevailing_wage'], dtype='object')

In [20]:
df["case_status"]

0           Denied
1        Certified
2           Denied
3           Denied
4        Certified
           ...
25475    Certified
25476    Certified
25477    Certified
25478    Certified
25479    Certified
Name: case_status, Length: 25480, dtype: object

In [21]:
df["case_status"].unique()

array(['Denied', 'Certified'], dtype=object)

In [22]:
# We have the two unique categories here, so we have encode that categorical to numerical as certified:0, denied:1

d = {'Certified':0, 'Denied':1}  # we have created a dictionary to convert the categorical values to numerical.

In [23]:
df["case_status"].map(d)   # It will replace(mapping) the categorical values from column with numerical value

0        1
1        0
2        1
3        1
4        0
        ..
25475    0
25476    0
25477    0
25478    0
25479    0
Name: case_status, Length: 25480, dtype: int64

In [45]:
# We will get NAN, inplace of 0's and 1's because we run the encoding code again.so we run it only once.


df["case_status"] = df["case_status"].map(d)   # It is overwrite the old "case_status" with new "case_status" column having numerical values

In [25]:
df

,case_id,continent,education_of_employee,has_job_experience,requires_job_training,no_of_employees,yr_of_estab,region_of_employment,prevailing_wage,unit_of_wage,full_time_position,case_status
0,EZYV01,Asia,High School,N,N,14513,2007,West,592.2029,Hour,Y,1
1,EZYV02,Asia,Master's,Y,N,2412,2002,Northeast,83425.6500,Year,Y,0
2,EZYV03,Asia,Bachelor's,N,Y,44444,2008,West,122996.8600,Year,Y,1
3,EZYV04,Asia,Bachelor's,N,N,98,1897,West,83434.0300,Year,Y,1
4,EZYV05,Africa,Master's,Y,N,1082,2005,South,149907.3900,Year,Y,0
...,...,...,...,...,...,...,...,...,...,...,...,...
25475,EZYV25476,Asia,Bachelor's,Y,Y,2601,2008,South,77092.5700,Year,Y,0
25476,EZYV25477,Asia,High School,Y,N,3274,2006,Northeast,279174.7900,Year,Y,0
25477,EZYV25478,Asia,Master's,Y,N,1121,1910,South,146298.8500,Year,N,0
25478,EZYV25479,Asia,Master's,Y,Y,1918,1887,West,86154.7700,Year,Y,0
25479,EZYV25480,Asia,Bachelor's,Y,N,3195,1960,Midwest,70876.9100,Year,Y,0

In [50]:
labels = df["continent"].unique()

for i in range(len(labels)):
    print(labels[i],i)
    d={labels[i]:i}

Asia 0
Africa 1
North America 2
Europe 3
South America 4
Oceania 5

In [51]:
d={labels[i]:i for i in range(len(labels))}
d

{'Asia': 0,
 'Africa': 1,
 'North America': 2,
 'Europe': 3,
 'South America': 4,
 'Oceania': 5}

In [52]:
df["continent"].map(d)

0        0
1        0
2        0
3        0
4        1
        ..
25475    0
25476    0
25477    0
25478    0
25479    0
Name: continent, Length: 25480, dtype: int64

In [53]:
df["continent"] = df["continent"].map(d)

In [54]:
df

,case_id,continent,education_of_employee,has_job_experience,requires_job_training,no_of_employees,yr_of_estab,region_of_employment,prevailing_wage,unit_of_wage,full_time_position,case_status
0,EZYV01,0,High School,N,N,14513,2007,West,592.2029,Hour,Y,Denied
1,EZYV02,0,Master's,Y,N,2412,2002,Northeast,83425.6500,Year,Y,Certified
2,EZYV03,0,Bachelor's,N,Y,44444,2008,West,122996.8600,Year,Y,Denied
3,EZYV04,0,Bachelor's,N,N,98,1897,West,83434.0300,Year,Y,Denied
4,EZYV05,1,Master's,Y,N,1082,2005,South,149907.3900,Year,Y,Certified
...,...,...,...,...,...,...,...,...,...,...,...,...
25475,EZYV25476,0,Bachelor's,Y,Y,2601,2008,South,77092.5700,Year,Y,Certified
25476,EZYV25477,0,High School,Y,N,3274,2006,Northeast,279174.7900,Year,Y,Certified
25477,EZYV25478,0,Master's,Y,N,1121,1910,South,146298.8500,Year,N,Certified
25478,EZYV25479,0,Master's,Y,Y,1918,1887,West,86154.7700,Year,Y,Certified
25479,EZYV25480,0,Bachelor's,Y,N,3195,1960,Midwest,70876.9100,Year,Y,Certified

In [55]:
df["continent"].unique()

array([0, 1, 2, 3, 4, 5], dtype=int64)

In [56]:
# For encoding the all the categorical columns we can write it as below by using for loop.

for i in cat[1:]:
    labels = df[i].unique()
    d={labels[i]:i for i in range(len(labels))}
    df[i]=df[i].map(d)

In [57]:
df

,case_id,continent,education_of_employee,has_job_experience,requires_job_training,no_of_employees,yr_of_estab,region_of_employment,prevailing_wage,unit_of_wage,full_time_position,case_status
0,EZYV01,0,0,0,0,14513,2007,0,592.2029,0,0,0
1,EZYV02,0,1,1,0,2412,2002,1,83425.6500,1,0,1
2,EZYV03,0,2,0,1,44444,2008,0,122996.8600,1,0,0
3,EZYV04,0,2,0,0,98,1897,0,83434.0300,1,0,0
4,EZYV05,1,1,1,0,1082,2005,2,149907.3900,1,0,1
...,...,...,...,...,...,...,...,...,...,...,...,...
25475,EZYV25476,0,2,1,1,2601,2008,2,77092.5700,1,0,1
25476,EZYV25477,0,0,1,0,3274,2006,1,279174.7900,1,0,1
25477,EZYV25478,0,1,1,0,1121,1910,2,146298.8500,1,1,1
25478,EZYV25479,0,1,1,1,1918,1887,0,86154.7700,1,0,1
25479,EZYV25480,0,2,1,0,3195,1960,3,70876.9100,1,0,1

- package(library) : **sklearn(scikit-learn)**
     
     - module : **Preprocessing**
          
            - class : **LableEncoder**
            
                   - method : **fit_transform**
                    
                    
    
**from package.module import class**

- from sklearn.preprocessing import LableEncoder

**fit_transform**


**fit**
- fit means used to finding the categorical values from column and by creating a dictionary of that categorical values for replacement with numerical values.


**transform**
- transform means it will used to convert the categorical values to numerical by taking support of dictionary.

In [60]:
df = pd.read_csv("Visadataset.csv")


from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
le.fit_transform(df["case_status"])

array([1, 0, 1, ..., 0, 0, 0])

In [62]:
df = pd.read_csv("Visadataset.csv")


from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
df["case_status"] = le.fit_transform(df["case_status"])
df

,case_id,continent,education_of_employee,has_job_experience,requires_job_training,no_of_employees,yr_of_estab,region_of_employment,prevailing_wage,unit_of_wage,full_time_position,case_status
0,EZYV01,Asia,High School,N,N,14513,2007,West,592.2029,Hour,Y,1
1,EZYV02,Asia,Master's,Y,N,2412,2002,Northeast,83425.6500,Year,Y,0
2,EZYV03,Asia,Bachelor's,N,Y,44444,2008,West,122996.8600,Year,Y,1
3,EZYV04,Asia,Bachelor's,N,N,98,1897,West,83434.0300,Year,Y,1
4,EZYV05,Africa,Master's,Y,N,1082,2005,South,149907.3900,Year,Y,0
...,...,...,...,...,...,...,...,...,...,...,...,...
25475,EZYV25476,Asia,Bachelor's,Y,Y,2601,2008,South,77092.5700,Year,Y,0
25476,EZYV25477,Asia,High School,Y,N,3274,2006,Northeast,279174.7900,Year,Y,0
25477,EZYV25478,Asia,Master's,Y,N,1121,1910,South,146298.8500,Year,N,0
25478,EZYV25479,Asia,Master's,Y,Y,1918,1887,West,86154.7700,Year,Y,0
25479,EZYV25480,Asia,Bachelor's,Y,N,3195,1960,Midwest,70876.9100,Year,Y,0

In [64]:
df = pd.read_csv("Visadataset.csv")


from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()

for i in cat[1:]:
    df[i] = le.fit_transform(df[i])
df

,case_id,continent,education_of_employee,has_job_experience,requires_job_training,no_of_employees,yr_of_estab,region_of_employment,prevailing_wage,unit_of_wage,full_time_position,case_status
0,EZYV01,1,2,0,0,14513,2007,4,592.2029,0,1,1
1,EZYV02,1,3,1,0,2412,2002,2,83425.6500,3,1,0
2,EZYV03,1,0,0,1,44444,2008,4,122996.8600,3,1,1
3,EZYV04,1,0,0,0,98,1897,4,83434.0300,3,1,1
4,EZYV05,0,3,1,0,1082,2005,3,149907.3900,3,1,0
...,...,...,...,...,...,...,...,...,...,...,...,...
25475,EZYV25476,1,0,1,1,2601,2008,3,77092.5700,3,1,0
25476,EZYV25477,1,2,1,0,3274,2006,2,279174.7900,3,1,0
25477,EZYV25478,1,3,1,0,1121,1910,3,146298.8500,3,0,0
25478,EZYV25479,1,3,1,1,1918,1887,4,86154.7700,3,1,0
25479,EZYV25480,1,0,1,0,3195,1960,1,70876.9100,3,1,0

In [66]:
df = pd.read_csv("Visadataset.csv")

df["education_of_employee"].unique()

array(['High School', "Master's", "Bachelor's", 'Doctorate'], dtype=object)

In [67]:
# If we apply Nominal Encoding i.e. LableEncoder on "education_of_employee", it will get fail 
# because  it is "Ordinal Data" means order(priority) between the column category values is very important.
# but nominal encoding can't understand that it encode the cateories by alphabetical order, and gives wrong priority to categories.


from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
df["education_of_employee"] = le.fit_transform(df["education_of_employee"])
df

,case_id,continent,education_of_employee,has_job_experience,requires_job_training,no_of_employees,yr_of_estab,region_of_employment,prevailing_wage,unit_of_wage,full_time_position,case_status
0,EZYV01,Asia,2,N,N,14513,2007,West,592.2029,Hour,Y,Denied
1,EZYV02,Asia,3,Y,N,2412,2002,Northeast,83425.6500,Year,Y,Certified
2,EZYV03,Asia,0,N,Y,44444,2008,West,122996.8600,Year,Y,Denied
3,EZYV04,Asia,0,N,N,98,1897,West,83434.0300,Year,Y,Denied
4,EZYV05,Africa,3,Y,N,1082,2005,South,149907.3900,Year,Y,Certified
...,...,...,...,...,...,...,...,...,...,...,...,...
25475,EZYV25476,Asia,0,Y,Y,2601,2008,South,77092.5700,Year,Y,Certified
25476,EZYV25477,Asia,2,Y,N,3274,2006,Northeast,279174.7900,Year,Y,Certified
25477,EZYV25478,Asia,3,Y,N,1121,1910,South,146298.8500,Year,N,Certified
25478,EZYV25479,Asia,3,Y,Y,1918,1887,West,86154.7700,Year,Y,Certified
25479,EZYV25480,Asia,0,Y,N,3195,1960,Midwest,70876.9100,Year,Y,Certified

In [72]:
df = pd.read_csv("Visadataset.csv")

df["education_of_employee"].unique()

array(['High School', "Master's", "Bachelor's", 'Doctorate'], dtype=object)

In [73]:
order =['High School', "Bachelor's", "Master's", 'Doctorate']

In [74]:
from sklearn.preprocessing import OrdinalEncoder
oe = OrdinalEncoder(categories=order)
df["education_of_employee"] = oe.fit_transform(df["education_of_employee"])   # It will gives error beacuse it need 2D but we provided 1D

ValueError: Expected 2D array, got 1D array instead:
array=['High School' "Master's" "Bachelor's" ... "Master's" "Master's"
 "Bachelor's"].
Reshape your data either using array.reshape(-1, 1) if your data has a single feature or array.reshape(1, -1) if it contains a single sample.

In [75]:
order =[['High School', "Bachelor's", "Master's", 'Doctorate']]

from sklearn.preprocessing import OrdinalEncoder
oe = OrdinalEncoder(categories=order)
df["education_of_employee"] = oe.fit_transform(df[["education_of_employee"]])

In [76]:
df

,case_id,continent,education_of_employee,has_job_experience,requires_job_training,no_of_employees,yr_of_estab,region_of_employment,prevailing_wage,unit_of_wage,full_time_position,case_status
0,EZYV01,Asia,0.0,N,N,14513,2007,West,592.2029,Hour,Y,Denied
1,EZYV02,Asia,2.0,Y,N,2412,2002,Northeast,83425.6500,Year,Y,Certified
2,EZYV03,Asia,1.0,N,Y,44444,2008,West,122996.8600,Year,Y,Denied
3,EZYV04,Asia,1.0,N,N,98,1897,West,83434.0300,Year,Y,Denied
4,EZYV05,Africa,2.0,Y,N,1082,2005,South,149907.3900,Year,Y,Certified
...,...,...,...,...,...,...,...,...,...,...,...,...
25475,EZYV25476,Asia,1.0,Y,Y,2601,2008,South,77092.5700,Year,Y,Certified
25476,EZYV25477,Asia,0.0,Y,N,3274,2006,Northeast,279174.7900,Year,Y,Certified
25477,EZYV25478,Asia,2.0,Y,N,1121,1910,South,146298.8500,Year,N,Certified
25478,EZYV25479,Asia,2.0,Y,Y,1918,1887,West,86154.7700,Year,Y,Certified
25479,EZYV25480,Asia,1.0,Y,N,3195,1960,Midwest,70876.9100,Year,Y,Certified