In [1]:
import pandas as pd
import numpy as np

df = pd.DataFrame({'x':[10,20,22,19,35,21,15,16,18,15]})
df

    x
0  10
1  20
2  22
3  19
4  35
5  21
6  15
7  16
8  18
9  15

In [2]:
df["x"].skew()

1.5067126791672831

### Transformation :- 
  - It is the process of converting the skewed distribution to normal distribution.
    
#### For Left Skewed Distribution :- 
   - 1. Exponential Transformation
   - 2. Power Transformation
   - 3. Box-Cox Transformation
    
#### For Right Skewed Distribution :- 
   - 1. Log Transformation
   - 2. Root Transformation
   - 3. Box-Cox Transformation

- The above data is skewed distributed data so, we need to convert that data to the normal distribution.
- For converting skewed distribution to normal distribution there are many techniques. 
- So apply that techniques we have to first identify which type of skewed distribution is this.
- The above data distribution is right skewed cause skewness is greater than 1.

### Right Skewed Distribution :-
 #### 1. Log Transformation
 - While applying log first we have to check the minimum value of that column.
 - If the minimum value is 0, then we have to add some neglegible value to that column's value otherwise it will not work because log of 0 is infinite.

In [3]:
df["x"].min()  # Here min value is not 0, so need not add negligilbe value to column(x), if 0 is there in column then we have add negligible value to that column.

10

In [4]:
df["x_log"] = np.log(df["x"])
df

    x     x_log
0  10  2.302585
1  20  2.995732
2  22  3.091042
3  19  2.944439
4  35  3.555348
5  21  3.044522
6  15  2.708050
7  16  2.772589
8  18  2.890372
9  15  2.708050

In [5]:
df["x_log"].skew()     # It is giving skewness is in [-1,1], so we have converted the skewed data to normal data using Log Transformation

0.24240211451944507

#### 2. Root Transformation
- It will apply first square root on every value of column if then also data distribution is not normal then apply further roots(cube root, 4th root, 5th root,...) untill the data distribution is Normally Distributed.

In [6]:
df["x_root"] = np.sqrt(df["x"])
df

    x     x_log    x_root
0  10  2.302585  3.162278
1  20  2.995732  4.472136
2  22  3.091042  4.690416
3  19  2.944439  4.358899
4  35  3.555348  5.916080
5  21  3.044522  4.582576
6  15  2.708050  3.872983
7  16  2.772589  4.000000
8  18  2.890372  4.242641
9  15  2.708050  3.872983

In [7]:
df["x_root"].skew()  # It is giving skewness is in [-1,1], so we have converted the skewed data to normal data using Root Transformation

0.9100955567245163

#### 3. Box-Cox Transformation
- It covert the all values from column to respected value calculated by the formula (x^λ - 1)/(λ - 1) 
- where lambda is between -5 to 5, except λ=1.
- The best lambda value for the transformation of skewed data to normal distribution is calculated within inside by Box-Cox i.e param return value of boxcox()

In [8]:
from scipy.stats import boxcox

df["x_boxcox"],param = boxcox(df["x"])
print("Labda Value", param)
df

Labda Value -0.18534732651138236

    x     x_log    x_root  x_boxcox
0  10  2.302585  3.162278  1.874273
1  20  2.995732  4.472136  2.298775
2  22  3.091042  4.690416  2.352996
3  19  2.944439  4.358899  2.269196
4  35  3.555348  5.916080  2.603859
5  21  3.044522  4.582576  2.326651
6  15  2.708050  3.872983  2.129185
7  16  2.772589  4.000000  2.168021
8  18  2.890372  4.242641  2.237711
9  15  2.708050  3.872983  2.129185

In [47]:
df1 = pd.DataFrame({'x':[10,20,22,1,10,15,15,16,18,15]})
df1

    x
0  10
1  20
2  22
3   1
4  10
5  15
6  15
7  16
8  18
9  15

In [48]:
df1["x"].skew()

-1.1055961509518397

- The above data is skewed distributed data so, we need to convert that data to the normal distribution.
- For converting skewed distribution to normal distribution there are many techniques. 
- So apply that techniques we have to first identify which type of skewed distribution is this.
- The above data distribution is left skewed cause skewness is less than 1.

### Left Skewed Distribution
#### 1. Exponential Transformation

In [58]:
df1["x_exp"] = np.exp(df1["x"])
df1

    x         x_exp  x_pow
0  10  2.202647e+04    100
1  20  4.851652e+08    400
2  22  3.584913e+09    484
3   1  2.718282e+00      1
4  10  2.202647e+04    100
5  15  3.269017e+06    225
6  15  3.269017e+06    225
7  16  8.886111e+06    256
8  18  6.565997e+07    324
9  15  3.269017e+06    225

In [59]:
df1["x_exp"].skew()

3.0637449992264574

#### 2. Power Transformation

In [60]:
df1["x_pow"] = df1["x"]**2
df1

    x         x_exp  x_pow
0  10  2.202647e+04    100
1  20  4.851652e+08    400
2  22  3.584913e+09    484
3   1  2.718282e+00      1
4  10  2.202647e+04    100
5  15  3.269017e+06    225
6  15  3.269017e+06    225
7  16  8.886111e+06    256
8  18  6.565997e+07    324
9  15  3.269017e+06    225

In [61]:
df1["x_pow"].skew()

0.15850041342186863

In [44]:
#### 3. Box-Cox Transformation

In [62]:
from scipy.stats import boxcox

df1["x_boxcox"],param = boxcox(df1["x"])
print("Labda Value", param)
df1

Labda Value 1.3436354673162583

    x         x_exp  x_pow   x_boxcox
0  10  2.202647e+04    100  15.675027
1  20  4.851652e+08    400  40.926239
2  22  3.584913e+09    484  46.619412
3   1  2.718282e+00      1   0.000000
4  10  2.202647e+04    100  15.675027
5  15  3.269017e+06    225  27.566833
6  15  3.269017e+06    225  27.566833
7  16  8.886111e+06    256  30.131454
8  18  6.565997e+07    324  35.425642
9  15  3.269017e+06    225  27.566833

In [63]:
df["x_boxcox"].skew()

-0.011231143838109267