In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
df = pd.read_csv("D:\Data Science by SRK\Omkar Sir 10.30AM Batch\EDA\Visadataset.csv")
df

,case_id,continent,education_of_employee,has_job_experience,requires_job_training,no_of_employees,yr_of_estab,region_of_employment,prevailing_wage,unit_of_wage,full_time_position,case_status
0,EZYV01,Asia,High School,N,N,14513,2007,West,592.2029,Hour,Y,Denied
1,EZYV02,Asia,Master's,Y,N,2412,2002,Northeast,83425.6500,Year,Y,Certified
2,EZYV03,Asia,Bachelor's,N,Y,44444,2008,West,122996.8600,Year,Y,Denied
3,EZYV04,Asia,Bachelor's,N,N,98,1897,West,83434.0300,Year,Y,Denied
4,EZYV05,Africa,Master's,Y,N,1082,2005,South,149907.3900,Year,Y,Certified
...,...,...,...,...,...,...,...,...,...,...,...,...
25475,EZYV25476,Asia,Bachelor's,Y,Y,2601,2008,South,77092.5700,Year,Y,Certified
25476,EZYV25477,Asia,High School,Y,N,3274,2006,Northeast,279174.7900,Year,Y,Certified
25477,EZYV25478,Asia,Master's,Y,N,1121,1910,South,146298.8500,Year,N,Certified
25478,EZYV25479,Asia,Master's,Y,Y,1918,1887,West,86154.7700,Year,Y,Certified
25479,EZYV25480,Asia,Bachelor's,Y,N,3195,1960,Midwest,70876.9100,Year,Y,Certified

### How to select one columns:

In [3]:
print(df["continent"])
print(df["continent"].shape)# 1D, It is in Series 

print(df[["continent"]])
print(df[["continent"]].shape)  # 2D, It is in DataFrame

print(df.iloc[:,1])    # 1D, It is in Series 
print(df.iloc[:,[1]])  # 2D, It is in DataFrame
print(df.loc[:,"continent"])    # 1D, It is in Series 
print(df.loc[:,["continent"]])  # 2D, It is in DataFrame

0          Asia
1          Asia
2          Asia
3          Asia
4        Africa
          ...
25475      Asia
25476      Asia
25477      Asia
25478      Asia
25479      Asia
Name: continent, Length: 25480, dtype: object
(25480,)
      continent
0          Asia
1          Asia
2          Asia
3          Asia
4        Africa
...         ...
25475      Asia
25476      Asia
25477      Asia
25478      Asia
25479      Asia

[25480 rows x 1 columns]
(25480, 1)
0          Asia
1          Asia
2          Asia
3          Asia
4        Africa
          ...
25475      Asia
25476      Asia
25477      Asia
25478      Asia
25479      Asia
Name: continent, Length: 25480, dtype: object
      continent
0          Asia
1          Asia
2          Asia
3          Asia
4        Africa
...         ...
25475      Asia
25476      Asia
25477      Asia
25478      Asia
25479      Asia

[25480 rows x 1 columns]
0          Asia
1          Asia
2          Asia
3          Asia
4        Africa
          ...
25475      Asia
25476      Asia
25477      Asia
25478      Asia
25479      Asia
Name: continent, Length: 25480, dtype: object
      continent
0          Asia
1          Asia
2          Asia
3          Asia
4        Africa
...         ...
25475      Asia
25476      Asia
25477      Asia
25478      Asia
25479      Asia

[25480 rows x 1 columns]

In [70]:
df.dtypes   # It will gives the Series of column names as row names and their datatypes as row values.

case_id                   object
continent                 object
education_of_employee     object
has_job_experience        object
requires_job_training     object
no_of_employees            int64
yr_of_estab                int64
region_of_employment      object
prevailing_wage          float64
unit_of_wage              object
full_time_position        object
case_status               object
dtype: object

In [5]:
df.dtypes.shape   # It shows above is in Series not in DataFrame

(12,)

In [6]:
df.dtypes.keys()

Index(['case_id', 'continent', 'education_of_employee', 'has_job_experience',
       'requires_job_training', 'no_of_employees', 'yr_of_estab',
       'region_of_employment', 'prevailing_wage', 'unit_of_wage',
       'full_time_position', 'case_status'],
      dtype='object')

In [68]:
df.dtypes.index

Index(['case_id', 'continent', 'education_of_employee', 'has_job_experience',
       'requires_job_training', 'no_of_employees', 'yr_of_estab',
       'region_of_employment', 'prevailing_wage', 'unit_of_wage',
       'full_time_position', 'case_status'],
      dtype='object')

In [8]:
df.dtypes.values

array([dtype('O'), dtype('O'), dtype('O'), dtype('O'), dtype('O'),
       dtype('int64'), dtype('int64'), dtype('O'), dtype('float64'),
       dtype('O'), dtype('O'), dtype('O')], dtype=object)

#### Coverting Series to DataFrame

In [9]:
keys = df.dtypes.keys().tolist()    # It will gives the list of all the columns in dataset
values = df.dtypes.values.tolist()  # It will gives the list of all the datatypes of each columns


pd.DataFrame(zip(keys,values),columns=["Culumn Names","DataTypes"])   # It will gives the dataframe of all the columns and their datatypes.

             Culumn Names DataTypes
0                 case_id    object
1               continent    object
2   education_of_employee    object
3      has_job_experience    object
4   requires_job_training    object
5         no_of_employees     int64
6             yr_of_estab     int64
7    region_of_employment    object
8         prevailing_wage   float64
9            unit_of_wage    object
10     full_time_position    object
11            case_status    object

In [10]:
pd.DataFrame(df.dtypes)   # It will convert the series to dataframe but the problem column names will became the index numbers not the column value

                             0
case_id                 object
continent               object
education_of_employee   object
has_job_experience      object
requires_job_training   object
no_of_employees          int64
yr_of_estab              int64
region_of_employment    object
prevailing_wage        float64
unit_of_wage            object
full_time_position      object
case_status             object

In [12]:
pd.DataFrame(df.dtypes).reset_index()   # It will reset the index numbers as integer values starting from 0 
                                     # and the old indexes will became the columns values with column name as "index".

                    index        0
0                 case_id   object
1               continent   object
2   education_of_employee   object
3      has_job_experience   object
4   requires_job_training   object
5         no_of_employees    int64
6             yr_of_estab    int64
7    region_of_employment   object
8         prevailing_wage  float64
9            unit_of_wage   object
10     full_time_position   object
11            case_status   object

In [54]:
dtypes = df.dtypes    # It will gives the Series of columns with their datatypes.
d = pd.DataFrame(dtypes).reset_index()
d.columns=["Column Name","DataTypes"]
d

              Column Name DataTypes
0                 case_id    object
1               continent    object
2   education_of_employee    object
3      has_job_experience    object
4   requires_job_training    object
5         no_of_employees     int64
6             yr_of_estab     int64
7    region_of_employment    object
8         prevailing_wage   float64
9            unit_of_wage    object
10     full_time_position    object
11            case_status    object

In [62]:
cat = []

for i,j in zip(d["Column Name"],d["DataTypes"]):
    if j=="object":
        cat.append(i)
cat

['case_id',
 'continent',
 'education_of_employee',
 'has_job_experience',
 'requires_job_training',
 'region_of_employment',
 'unit_of_wage',
 'full_time_position',
 'case_status']

In [57]:
dtypes=df.dtypes
keys=dtypes.keys().tolist()
values=dtypes.values.tolist()
cat=[]
for i,j in zip(keys,values):
    if j=='object':
        cat.append(i)

cat

['case_id',
 'continent',
 'education_of_employee',
 'has_job_experience',
 'requires_job_training',
 'region_of_employment',
 'unit_of_wage',
 'full_time_position',
 'case_status']

In [72]:
[i for i in zip(keys,values) if j=="object"]

[('case_id', dtype('O')),
 ('continent', dtype('O')),
 ('education_of_employee', dtype('O')),
 ('has_job_experience', dtype('O')),
 ('requires_job_training', dtype('O')),
 ('no_of_employees', dtype('int64')),
 ('yr_of_estab', dtype('int64')),
 ('region_of_employment', dtype('O')),
 ('prevailing_wage', dtype('float64')),
 ('unit_of_wage', dtype('O')),
 ('full_time_position', dtype('O')),
 ('case_status', dtype('O'))]

### select_dtypes():

    - df.select_dtypes(include=None, exclude=None) -> Return a subset of the DataFrame's columns based on the column dtypes.
    
    - This function is used to collect the columns from the datasets depending on their datatypes.
    - If we use 'include' parameter then we can get the all the columns of that included datatypes from dataset
    - If we use 'exclude' parameter then we we get the all the columns of other datatypes excluding the excluded datatype from the dataset.

In [15]:
df.select_dtypes(include="object")   # It will gives the data of all the columns which have "object" datatype only.

,case_id,continent,education_of_employee,has_job_experience,requires_job_training,region_of_employment,unit_of_wage,full_time_position,case_status
0,EZYV01,Asia,High School,N,N,West,Hour,Y,Denied
1,EZYV02,Asia,Master's,Y,N,Northeast,Year,Y,Certified
2,EZYV03,Asia,Bachelor's,N,Y,West,Year,Y,Denied
3,EZYV04,Asia,Bachelor's,N,N,West,Year,Y,Denied
4,EZYV05,Africa,Master's,Y,N,South,Year,Y,Certified
...,...,...,...,...,...,...,...,...,...
25475,EZYV25476,Asia,Bachelor's,Y,Y,South,Year,Y,Certified
25476,EZYV25477,Asia,High School,Y,N,Northeast,Year,Y,Certified
25477,EZYV25478,Asia,Master's,Y,N,South,Year,N,Certified
25478,EZYV25479,Asia,Master's,Y,Y,West,Year,Y,Certified
25479,EZYV25480,Asia,Bachelor's,Y,N,Midwest,Year,Y,Certified

In [17]:
cat = df.select_dtypes(include="object")   # It will gives table(dataframe) of all the categorical columns 
cat

,case_id,continent,education_of_employee,has_job_experience,requires_job_training,region_of_employment,unit_of_wage,full_time_position,case_status
0,EZYV01,Asia,High School,N,N,West,Hour,Y,Denied
1,EZYV02,Asia,Master's,Y,N,Northeast,Year,Y,Certified
2,EZYV03,Asia,Bachelor's,N,Y,West,Year,Y,Denied
3,EZYV04,Asia,Bachelor's,N,N,West,Year,Y,Denied
4,EZYV05,Africa,Master's,Y,N,South,Year,Y,Certified
...,...,...,...,...,...,...,...,...,...
25475,EZYV25476,Asia,Bachelor's,Y,Y,South,Year,Y,Certified
25476,EZYV25477,Asia,High School,Y,N,Northeast,Year,Y,Certified
25477,EZYV25478,Asia,Master's,Y,N,South,Year,N,Certified
25478,EZYV25479,Asia,Master's,Y,Y,West,Year,Y,Certified
25479,EZYV25480,Asia,Bachelor's,Y,N,Midwest,Year,Y,Certified

In [66]:
df.select_dtypes(include="object").columns   # # It will gives list of all the categorical columns

Index(['case_id', 'continent', 'education_of_employee', 'has_job_experience',
       'requires_job_training', 'region_of_employment', 'unit_of_wage',
       'full_time_position', 'case_status'],
      dtype='object')

In [16]:
df.select_dtypes(exclude="object")   # It will gives the data of all the columns which don't have  "object" as datatype(means it will gives all others datatypes columns data execpt "object" datatype.).

       no_of_employees  yr_of_estab  prevailing_wage
0                14513         2007         592.2029
1                 2412         2002       83425.6500
2                44444         2008      122996.8600
3                   98         1897       83434.0300
4                 1082         2005      149907.3900
...                ...          ...              ...
25475             2601         2008       77092.5700
25476             3274         2006      279174.7900
25477             1121         1910      146298.8500
25478             1918         1887       86154.7700
25479             3195         1960       70876.9100

[25480 rows x 3 columns]

In [18]:
num = df.select_dtypes(exclude="object")  # It will gives table(dataframe) of all the numerical columns
num

       no_of_employees  yr_of_estab  prevailing_wage
0                14513         2007         592.2029
1                 2412         2002       83425.6500
2                44444         2008      122996.8600
3                   98         1897       83434.0300
4                 1082         2005      149907.3900
...                ...          ...              ...
25475             2601         2008       77092.5700
25476             3274         2006      279174.7900
25477             1121         1910      146298.8500
25478             1918         1887       86154.7700
25479             3195         1960       70876.9100

[25480 rows x 3 columns]

In [64]:
df.select_dtypes(exclude="object").columns   # It will gives list of all columns which does not have 'object' as datatype.

Index(['no_of_employees', 'yr_of_estab', 'prevailing_wage'], dtype='object')

#### unique() : 

- It is function used to gives all the unique categories from the column.

In [19]:
df["continent"].unique()

array(['Asia', 'Africa', 'North America', 'Europe', 'South America',
       'Oceania'], dtype=object)

In [20]:
df["continent"].nunique()

6

In [21]:
u = df["continent"].unique()

In [22]:
df["continent"]=="Asia"    # It will gives the True for every value of continent column which is equal to 'True'. and False for not equal to 'Asia'

0         True
1         True
2         True
3         True
4        False
         ...
25475     True
25476     True
25477     True
25478     True
25479     True
Name: continent, Length: 25480, dtype: bool

In [23]:
sum(df["continent"]=="Asia")  # It will gives count of total values which is equal to 'Asia'

16861

In [24]:
# Similarly do above for other classes(/categories) from continent colm.#

In [25]:
# Finding count value of each unique category in column


lables = df["continent"].unique()
counts=[]

for i in lables:
    cond = df["continent"]==i
    counts.append(sum(cond))
    
    
counts

[16861, 551, 3292, 3732, 852, 192]

In [26]:
category = df["continent"].unique()
category

array(['Asia', 'Africa', 'North America', 'Europe', 'South America',
       'Oceania'], dtype=object)

In [27]:
d1 = pd.DataFrame(zip(category,counts),columns=(["Continent","counts"]))   # Creating a dataframe of unique categories and their total counts.
d1

       Continent  counts
0           Asia   16861
1         Africa     551
2  North America    3292
3         Europe    3732
4  South America     852
5        Oceania     192

#### value_counts():

- We can get value conuts of each unique category by using value_counts() function easily.

In [28]:
df["continent"].value_counts()

continent
Asia             16861
Europe            3732
North America     3292
South America      852
Africa             551
Oceania            192
Name: count, dtype: int64

#### groupby():

- df.groupby(
    by=None,
    axis: 'Axis' = 0,
    level: 'IndexLabel | None' = None,
    as_index: 'bool' = True,
    sort: 'bool' = True,
    group_keys: 'bool' = True,
    observed: 'bool' = False,
    dropna: 'bool' = True,
)

- It is a function used when we want to group(set) of all similar(unique) categories(classes) seperately.

In [29]:
df.groupby("continent").size()

continent
Africa             551
Asia             16861
Europe            3732
North America     3292
Oceania            192
South America      852
dtype: int64

In [30]:
df.size

305760

In [31]:
df["continent"].size

25480

In [42]:
# Combining all three methods for counting unique values from a column

# Method-1 :

lables = df["continent"].unique()
counts=[]

for i in lables:
    cond = df["continent"]==i
    counts.append(sum(cond))
    

print(counts)
print("==================")

# Method-2 :

print(df["continent"].value_counts())
print("==================")

# Method-3 : 

print(df.groupby("continent").size())

[16861, 551, 3292, 3732, 852, 192]
==================
continent
Asia             16861
Europe            3732
North America     3292
South America      852
Africa             551
Oceania            192
Name: count, dtype: int64
==================
continent
Africa             551
Asia             16861
Europe            3732
North America     3292
Oceania            192
South America      852
dtype: int64