In [1]:
import numpy as np
import pandas as pd

d = {"Names":["sai","tej","ram","jay"],
    "Age":[10,20,32,23],
    "City":["hyd","pune","mum","ben"]}

df = pd.DataFrame(d)
df

  Names  Age  City
0   sai   10   hyd
1   tej   20  pune
2   ram   32   mum
3   jay   23   ben

In [2]:
d = {"Names":["sai",None,"ram","jay"],
    "Age":[None,20,24,23],
    "City":["hyd","pune",None,"ben"]}

df11 = pd.DataFrame(d)
df11.to_csv("df11.csv")
df11

  Names   Age  City
0   sai   NaN   hyd
1  None  20.0  pune
2   ram  24.0  None
3   jay  23.0   ben

In [3]:
df.dtypes

Names    object
Age       int64
City     object
dtype: object

In [4]:
d = {"Names":["sai","tej",np.NaN,"jay"],
    "Age":[10,20,np.NaN,23],
    "City":["hyd","pune","mum",np.NaN]}

df2 = pd.DataFrame(d)
df2.to_csv("df2.csv")
df2

  Names   Age  City
0   sai  10.0   hyd
1   tej  20.0  pune
2   NaN   NaN   mum
3   jay  23.0   NaN

# 'None' is used when we want to pass null or null value is available in Categorical columns.
# 'np.nan' is used when we want to pass null or null value is available in numerical columns.

In [5]:
20 + 20

40

In [6]:
20 + None

TypeError: unsupported operand type(s) for +: 'int' and 'NoneType'

In [7]:
20 + np.nan # nan is applicable on numerical data

nan

In [8]:
"sam" + "aj"

'samaj'

In [9]:
"sam" + None

TypeError: can only concatenate str (not "NoneType") to str

In [10]:
"sam" + np.nan

TypeError: can only concatenate str (not "float") to str

In [11]:
a1 = np.array([10,11,12])
a2 = np.array([10,20,np.nan])
a3 = np.array(["sam","ram",np.nan])
a4 = np.array(["sam","ram",None])

In [12]:
np.sum(a1)

33

In [13]:
np.sum(a2)

nan

In [14]:
np.sum(a3)

UFuncTypeError: ufunc 'add' did not contain a loop with signature matching types (dtype('<U32'), dtype('<U32')) -> None

In [15]:
np.sum(a4)

TypeError: can only concatenate str (not "NoneType") to str

#### astype

In [16]:
d2 = pd.DataFrame({"Result":['pass','fail','pass','fail']})
d2

  Result
0   pass
1   fail
2   pass
3   fail

In [17]:
d2["Result1"] = d2["Result"].map({"fail":0.0,"pass":1.0})
d2

  Result  Result1
0   pass      1.0
1   fail      0.0
2   pass      1.0
3   fail      0.0

In [18]:
d2["Result_int"] = d2["Result1"].astype("int")
d2

  Result  Result1  Result_int
0   pass      1.0           1
1   fail      0.0           0
2   pass      1.0           1
3   fail      0.0           0

In [19]:
d2["Result_str"] = d2["Result1"].astype("str")
d2

  Result  Result1  Result_int Result_str
0   pass      1.0           1        1.0
1   fail      0.0           0        0.0
2   pass      1.0           1        1.0
3   fail      0.0           0        0.0

In [20]:
d2.dtypes

Result         object
Result1       float64
Result_int      int32
Result_str     object
dtype: object

# while replacing the "null" values from columns :

1. If the column is categorical(object type) then we have to use 'Mode' only.
2. If the column is Numerical(float,int) then we have to apply 'Mean' or 'median' depending on situation.
3. But if the column is converted from categorical to Numerical(specially to int datatype) then we can to apply 'Mean' or 'median' or 'Mode also depending on situation.

In [24]:
df2.isnull()

   Names    Age   City
0  False  False  False
1  False  False  False
2   True   True  False
3  False  False   True

#### fillna() :

df2.fillna(
    value: 'Hashable | Mapping | Series | DataFrame' = None,
    *,
    method: 'FillnaOptions | None' = None,
    axis: 'Axis | None' = None,
    inplace: 'bool' = False,
    limit: 'int | None' = None,
    downcast: 'dict | None' = None,
)

In [26]:
df2.fillna(20) # It is not good way to fill th null values beacsuse it is giving qll the null value are same which is not good.

  Names   Age  City
0   sai  10.0   hyd
1   tej  20.0  pune
2    20  20.0   mum
3   jay  23.0    20

In [29]:
#### Fill with random value based on columns.
# - First select the column then fill the null value


df2["Names"].fillna("Ram")

# But filling the null value with random value is not a good approach, it is not recommanded.

0    sai
1    tej
2    Ram
3    jay
Name: Names, dtype: object

#### Methods to fill the null values

- ffill : propagate last valid observation forward to next valid means it will fill the null value by exactly last(just before) value(observation) of that null from the same column in which the null from.

- bfill : backfill / bfill: use next valid observation to fill gap means it will fill the null value by exactly next(just after) value(observation) of that null from the same column in which the null from.

- backfill
- pad

In [30]:
df2.bfill(20)

TypeError: DataFrame.bfill() takes 1 positional argument but 2 were given

In [34]:
df2

  Names   Age  City
0   sai  10.0   hyd
1   tej  20.0  pune
2   NaN   NaN   mum
3   jay  23.0   NaN

In [32]:
df2.fillna(method="bfill")    #it will fill the null value by exactly next(just after) value(observation) of that null from the same column in which the null from.

  Names   Age  City
0   sai  10.0   hyd
1   tej  20.0  pune
2   jay  23.0   mum
3   jay  23.0   NaN

In [33]:
df2.fillna(method="ffill")   #it will fill the null value by exactly last(just before) value(observation) of that null from the same column in which the null from.

  Names   Age  City
0   sai  10.0   hyd
1   tej  20.0  pune
2   tej  20.0   mum
3   jay  23.0   mum

In [35]:
# It is also not good way to replace null value.
# So we should go with mean,median,mode.

#### Mean - Median - Mode for flll Null value :

- Mean is used when continous column is there.

- Median is used when continous column has outliers.

- Mode is used when categorical column is there.

In [36]:
df2.fillna(df["Age"].mean())

   Names    Age   City
0    sai  10.00    hyd
1    tej  20.00   pune
2  21.25  21.25    mum
3    jay  23.00  21.25

In [37]:
df2["Age"].fillna(df["Age"].mean())

0    10.00
1    20.00
2    21.25
3    23.00
Name: Age, dtype: float64

In [38]:
df2["Age"].fillna(df["Age"].median())

0    10.0
1    20.0
2    21.5
3    23.0
Name: Age, dtype: float64

#### Adding a new row to table using 'loc'.

In [89]:
row = ["jay",20,"hyd"]

df2.loc[len(df)]=row
df2

  Names   Age  City
0   sai  10.0   hyd
1   tej  20.0  pune
2   NaN   NaN   mum
3   jay  23.0   NaN
4   jay  20.0   hyd

In [88]:
df2["Names"].fillna(df["Names"].mode())

0    sai
1    tej
2    jay
3    jay
4    jay
Name: Names, dtype: object

In [93]:
mode = df["Names"].mode()
print(mode)

df2["Names"].fillna(mode)

0    jay
1    ram
2    sai
3    tej
Name: Names, dtype: object

0    sai
1    tej
2    sai
3    jay
4    jay
Name: Names, dtype: object

- whenever we calculate Mode, the output of mode is in series format

- so while filling null with mode, it will makes complicate

- so we should convert that mode output which is in series into values, and then replace the nill value with mode.

In [95]:
mode = df["Names"].mode()

df2["Names"].fillna(mode.values[0])

0    sai
1    tej
2    jay
3    jay
4    jay
Name: Names, dtype: object

#### Filling Null with Bivariate Analysis

- Always We should not replace the Null value with mean, median, mode by considering only one column.

- Some time we have to consider the other columns of dataset also to get more accurate value to replace Null value.

- below is the example on that

In [52]:
d = {"Education":["mbbs","engg","mbbs","engg","engg"],"Salary":[70,40,80,50,np.nan]}

df5 = pd.DataFrame(d)
df5

  Education  Salary
0      mbbs    70.0
1      engg    40.0
2      mbbs    80.0
3      engg    50.0
4      engg     NaN

In [70]:
df5["Salary"].fillna(df5["Salary"].mean())   # It will not gives more approprite value to replace missing value beacuse it will consider all the values in "Salary" column while calculating mean
                                             # But there are different categeries in "Education" column which affect the "Salary" column's values completely
                                             # So have to consider that categories and by making group of similar categories we should fill the missing values from "Salary" colm.
                                             # Ex. In "Education" colm 'mbbs' & 'engg', two categories are there which are completely different and and which will impact on their salary, so whilw calculating engg's salary we shold noy conider the mbbs category.

0    70.0
1    40.0
2    80.0
3    50.0
4    60.0
Name: Salary, dtype: float64

In [105]:
# So the correct way is 

mean = df5.groupby(["Education"])["Salary"].mean()
print(mean)

df5["Salary"].fillna(mean[0])

Education
engg    45.0
mbbs    75.0
Name: Salary, dtype: float64

0    70.0
1    40.0
2    80.0
3    50.0
4    45.0
Name: Salary, dtype: float64

#### linear Interpolation to fill the Null :

In [61]:
df6 = pd.DataFrame([10,np.nan,np.nan,40,50], columns=["Values"])
df6

   Values
0    10.0
1     NaN
2     NaN
3    40.0
4    50.0

In [62]:
df6["Values"].interpolate(method="linear")

0    10.0
1    20.0
2    30.0
3    40.0
4    50.0
Name: Values, dtype: float64

#### interpolate(method="linear")

- It is used to replace the null values by considering the side by values(previous & next values of null value)


- It will calculate the range between tha last(previous) & next values of the null value(s) and count the number of missing value(s) in that range.

- Then it will divide that range value by the no. of missing values plus 1, And then replace the missing values by adding that number to the previos value of that perticluar missing value.


- Ex.
     - In above dataframe,
       
       - range = 40-10 (40 is next value of missing value and 10 is previous. )
             = 30
   
       - no. of missing values = 2 
       
       - adding value = 30/(2+1) = 10
       
       - so 1st null value is replaced by : previous value + adding value = 10 + 10 = 20
       
       - 2nd null value is replaced by : it's previuos value(i.e. 1st null) + adding_value = 20 + 10 = 30
       
       - beacuse of this we get missing values 20 & 30.

In [68]:
# But the linear interpolation is not properly work when we have misiing value at the last of columns.
# It will replace the that last missing value with the previous valid column value.

df6 = pd.DataFrame([10,np.nan,np.nan,40,np.nan,50,np.nan], columns=["Values"])
df6

   Values
0    10.0
1     NaN
2     NaN
3    40.0
4     NaN
5    50.0
6     NaN

In [67]:
df6["Values"].interpolate(method="linear")    # It will replace the last null with the valid value i.e. 50

0    10.0
1    20.0
2    30.0
3    40.0
4    45.0
5    50.0
6    50.0
Name: Values, dtype: float64

#### KNNImputer

- sklearn-imputer-KNNImputer